#!/bin/sh
'''exec' "/Users/akanksha/Downloads/final dataset-4/venv_mac/bin/python3" "$0" "$@"
' '''
import sys
from fastapi.cli import main
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(main())
