#!/Users/akanksha/Downloads/final dataset-4/venv_mac/bin/python3
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
